language: elixir
elixir:
  - 1.12.3
otp_release:
  - 24.0.2
env:
  - MIX_ENV=test
script:
  - mix do deps.get, coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - _build
  - deps
